# Generated by Django 5.2.7 on 2025-11-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_promocion_perfilempleado_rol_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='productos',
            field=models.ManyToManyField(related_name='promociones', through='core.ProductoPromocion', to='core.producto'),
        ),
    ]
