# Generated by Django 5.2.7 on 2025-11-07 05:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_promocion_productos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteraccionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('vista_producto', 'Vista de Producto'), ('solicitud_simple', 'Pedido Simple (en Stock)'), ('solicitud_personalizada', 'Pedido Personalizado'), ('compra_final', 'Pago/Compra Final')], max_length=30, verbose_name='Tipo de Interacción')),
                ('detalles', models.TextField(blank=True, null=True, verbose_name='Detalles/Datos del Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interacción de Cliente',
                'verbose_name_plural': 'Interacciones de Clientes',
                'ordering': ['-fecha'],
            },
        ),
    ]
